#!/usr/bin/env python

import os
import sys
import code
import getpass

here = os.path.dirname(os.path.dirname(__file__))
sys.path.append(here)

from bitmm.xwrap.client import XWrap

client = XWrap(baseurl='http://localhost:8001')
apikey = raw_input('apikey: ')
apisecret = getpass.getpass('apisecret: ')
account = client.account(apikey, apisecret)
exchange = raw_input('Exchange (mtgox/bitstamp): ')
backends = account.list_backends(exchange)
if not backends:
    apiusername = raw_input('API username (leave empty if not appropriate):\n')
    apikey_ = raw_input('API key for the exchange:\n')
    apisecret_ = raw_input('API secret for the exchange:\n')
    backend = account.create_backend(
        exchange, apiusername, apikey_, apisecret_)
else:
    backend = backends[0]

code.interact(
    'Use the `client` variable for public methods, `account` for private '
    'methods and `backend` for the back-end (exchange) specific ones.',
    local={'client': client, 'account': account, 'backend': backend})
