#!/usr/bin/env python

import os
import sys
import code
import getpass

here = os.path.dirname(os.path.dirname(__file__))
sys.path.append(here)

from bitmm.xwrap.client import XWrap

client = XWrap(baseurl='http://localhost:8001')
username = raw_input('Username: ')
passwd = getpass.getpass('Password: ')
account = client.account(username, passwd)
exchange = raw_input('Exchange (mtgox/bitstamp): ')
backends = account.list_backends(exchange)
if not backends:
    apiusername = raw_input('API username (leave empty if not appropriate):\n')
    apikey = raw_input('API key:\n')
    apisecret = raw_input('API secret:\n')
    backend = account.create_backend(
        exchange, apiusername, apikey, apisecret)
else:
    backend = backends[0]

code.interact(
    'Use the `client` variable for public methods, `account` for private '
    'methods and `backend` for the back-end (exchange) specific ones.',
    local={'client': client, 'account': account, 'backend': backend})
